<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\generator\\definition\\commenttrait' => '/../src/Definition/CommentTrait.php',
                'rapture\\generator\\definition\\commontrait' => '/../src/Definition/CommonTrait.php',
                'rapture\\generator\\phpclass' => '/../src/PhpClass.php',
                'rapture\\generator\\phpcomment' => '/../src/PhpComment.php',
                'rapture\\generator\\phpmethod' => '/../src/PhpMethod.php',
                'rapture\\generator\\phpproperty' => '/../src/PhpProperty.php',
                'rapture\\generator\\phprender' => '/../src/PhpRender.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
